### PR TITLE
Added support for reading M3U files in IPTV format.

### PR DESCRIPTION
**Pull request by shnorbluk**
I added support for IPTV M3U format. It is used by players like Kodi or Perfect Player to watch free or paid TV channels. It can replace air or cable channels. You can see an example in the README.md of my fork repository (https://github.com/shnorbluk/m3u/blob/master/README.md).
It can only read IPTV files for now but I intend to implement the write feature soon.
Please accept my pull request. Thank you!

### CODE REVIEW

**Comment by shnorbluk** [comment]
As said in my previous pull request, I implemented writing IPTV files too.
Please accept my pull request. Thank you!

**Comment by mitchmindtree** [comment]
So sorry about the lack of activity on this, this crate tends to slip my mind!

I think I'd be happy to merge this if we could add it behind an opt-in `iptv` feature flag perhaps?

**Comment by shnorbluk** [comment]
Sorry I became busy now too :) 
I don't understand your reply. Can you please explain what you mean by "an opt-in iptv feature flag perhaps"? Thank you.

**Comment by mitchmindtree** [comment]
No worries!

> Can you please explain what you mean by "an opt-in iptv feature flag perhaps"?

By this, I meant that perhaps we could add support for IPTV behind a [cargo feature](https://doc.rust-lang.org/cargo/reference/features.html).

**Comment by shnorbluk** [comment]
OK I did'nt know that. Do as you want. But why do you want to implement it this way? You find it a too "exotic" feature to burden the library with it?
Anyway, it is no problem to me as long as I can import it in my project.
Thank you.

**Comment by shnorbluk** [comment]
To help you on integrating my changes, considering your answers, I close this PR to open 3 more simple ones, with little and clear commits:
- 1 for fixes on warnings, clippy alerts and code enhancements
- 1 for a little change that may slightly break compatibility for some clients (they must pass &mut buffer instead of buffer) but is important
- 1 to add iptv capabilities as a cargo feature. All iptv specific code has been isolated to their own modules, to keep your structure unchanged.

The first 2 are needed for the third one. Don't hesitate to add any remarks. 
Thank you.

**Pull request closed without merging**
